# Generated by Django 4.1.7 on 2023-09-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='data_pedido',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='store.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='tenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tenis'),
        ),
    ]
