# Generated by Django 4.1.7 on 2023-09-21 00:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0002_remove_pedido_complete_remove_pedido_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='zip_code',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='city',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='address',
            new_name='logradouro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='preco_unitario',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuarios_permissoes', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.usuario', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.usuario'),
        ),
    ]
