# Generated by Django 4.1.7 on 2023-11-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_zip_code_endereco_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenis',
            old_name='imagem',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='tenis',
            old_name='preco',
            new_name='precoProd',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='tenis',
            name='descProd',
            field=models.CharField(default=1, max_length=300, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenis',
            name='filter',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenis',
            name='home',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenis',
            name='img2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenis',
            name='img3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenis',
            name='img4',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenis',
            name='nomeProd',
            field=models.CharField(default=1, max_length=300, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenis',
            name='stock',
            field=models.IntegerField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
