# Generated by Django 4.1.7 on 2023-11-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_imagem_tenis_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenis',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='home',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='stock',
        ),
    ]
